Add PlatformCheckbox
stryder-dev/flutter_platform_widgets pull request #417
Opened 2023-06-17 06:11 UTC by bookshiyi

2023-06-27 06:10 UTC, aqwert requested changes

2023-06-27 06:10 UTC, aqwert commented on lib/src/platform_checkbox.dart
> +  }) : assert(tristate || value != null);
Need to remove this assert

2023-06-27 06:10 UTC, aqwert commented on lib/src/platform_checkbox.dart
> +  }) : assert(tristate || value != null);
Need to remove this assert. See below why

2023-06-27 06:10 UTC, aqwert commented on lib/src/platform_checkbox.dart
> +    final data = material?.call(context, platform(context));
Need to put the assert here that combines the properties as a result from the widget props and the data props.

```
final tristate = data?.tristate ?? this.tristate;
final value = data?.value ?? this.value;
assert(tristate || value != null);

```

2023-06-27 06:10 UTC, aqwert commented on lib/src/platform_checkbox.dart
> +      tristate: data?.tristate ?? tristate,
```suggestion
      value: value,
      tristate: ristate,
```

2023-06-27 06:10 UTC, aqwert commented on lib/src/platform_checkbox.dart
> +    final data = cupertino?.call(context, platform(context));
Need to do the same here in the same way for material for adding the assert

2023-07-01 07:53 UTC, aqwert commented
Since the previous PR was merged, could you rebase to fix the conflicts. Thanks

2023-07-02 02:35 UTC, bookshiyi commented
I have resolved the conflict.

2023-07-02 07:18 UTC, merged