Add PlatformRadio
stryder-dev/flutter_platform_widgets pull request #418
Opened 2023-06-17 06:11 UTC by bookshiyi

2023-06-27 06:27 UTC, aqwert requested changes

2023-06-27 06:27 UTC, aqwert commented on lib/src/platform_radio.dart
> +    this.toggleable = false,
```suggestion
    this.toggleable,
```
It cannot be preset since it will interfere with the widget property `data.toggleable ?? toggleable`

2023-06-27 06:27 UTC, aqwert commented on lib/src/platform_radio.dart
> +  final bool toggleable;
```suggestion
  final bool? toggleable;
```

2023-06-27 06:27 UTC, aqwert commented on lib/src/platform_radio.dart
> +    this.autofocus = false,
```suggestion
    this.autofocus,
```

2023-06-27 06:27 UTC, aqwert commented on lib/src/platform_radio.dart
> +  final bool autofocus;
```suggestion
  final bool? autofocus;
```

2023-06-27 06:27 UTC, aqwert commented on lib/src/platform_radio.dart
> +    super.toggleable = false,
```suggestion
    super.toggleable,
```

2023-06-27 06:27 UTC, aqwert commented on lib/src/platform_radio.dart
> +    super.autofocus = false,
```suggestion
    super.autofocus,
```

2023-06-27 06:27 UTC, aqwert commented on lib/src/platform_radio.dart
> +    super.toggleable = false,
```suggestion
    super.toggleable,
```

2023-06-27 06:27 UTC, aqwert commented on lib/src/platform_radio.dart
> +    super.autofocus = false,
```suggestion
    super.autofocus,
```

2023-06-29 07:47 UTC, bookshiyi commented
@aqwert  Thank you for code review. I have modified and submitted the new code.

2023-07-01 07:35 UTC, aqwert approved these changes
Thanks. I will merge it in and do a final check locally

2023-07-01 07:35 UTC, merged