Add PlatformSliverAppBar class with example
stryder-dev/flutter_platform_widgets pull request #427
Opened 2023-07-15 12:38 UTC by bookshiyi

Inspired by PR #425.

2023-07-15 12:41 UTC, bookshiyi commented on lib/src/platform_sliver_app_bar.dart
> +const Color _kDefaultNavBarBorderColor = Color(0x4D000000);
Regarding these local variables, I didn't find a better solution, so I had to copy and paste them here intact.

2023-07-15 12:53 UTC, bookshiyi commented on lib/src/platform_sliver_app_bar.dart
> +}
Regarding these local variables, I didn't find a better solution, so I had to copy and paste them here intact.

2024-01-24 09:27 UTC, aqwert approved these changes
Thanks

2024-01-24 09:27 UTC, aqwert commented
Could you rebase. Sorry for the time it has taken to review

2024-01-24 09:28 UTC, aqwert requested changes
Can you rebase please and resolve the conflicts

2024-01-24 09:45 UTC, bookshiyi commented
> Can you rebase please and resolve the conflicts

The conflicts has been resolved without rebase. How do you think about this?

2024-01-31 09:47 UTC, aqwert approved these changes
Thanks.LGTM

2024-01-31 09:47 UTC, merged